[package]
name = "r6"
version = "0.0.1"
authors = [ "kimhyunkang@gmail.com" ]

[dependencies]
num = "0.1"
phf = "0.7"
phf_macros = "0.7"
regex = "0.1"
log = "0.3"
enum_primitive = "0.1"
copperline = "0.3"
unicode_categories = "0.1"
immutable-map = "0.1"

[dev-dependencies]
env_logger = "0.3"
