[package]
name = "r6"
version = "0.0.1"
authors = [ "kimhyunkang@gmail.com" ]

[dependencies]
num = "~0.1.10"
phf = "~0.6.1"
phf_macros = "~0.6.1"
regex = "0.1.21"
regex_macros = "~0.1.5"
log = "~0.3"

[dev-dependencies]
env_logger = "~0.3"
